using System;
using System.Collections.Generic;

namespace NoRealm.Phi.Metadata.Builder
{
    /// <summary>
    /// Represent content generated by <see cref="IMetadataBuilder"/>
    /// </summary>
    public interface IMetadataContent
    {
        /// <summary>
        /// Get set of excluded names.
        /// </summary>
        /// <returns>A set of excluded names; otherwise empty set.</returns>
        IEnumerable<string> GetExcludedGroup(ExcludeGroup excludeGroup);

        /// <summary>
        /// Get set of excluded types.
        /// </summary>
        /// <returns>A set of excluded types; otherwise empty set.</returns>
        IEnumerable<Type> GetExcludedTypes();

        /// <summary>
        /// Get types to be added into cache.
        /// </summary>
        /// <returns>A list of pairs requested types; otherwise empty list.</returns>
        IEnumerable<(Type TargetType, bool DeepScan)> GetTypesToCache();

        /// <summary>
        /// Get features details
        /// </summary>
        /// <returns>A sequence of feature details; otherwise empty sequence.</returns>
        IEnumerable<IFeatureDetails> GetFeatures();
    }
}
